spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/commentdb
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      postServiceCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 50
        failureRateThreshold: 60
        waitDurationInOpenState: 5000
      commentServiceCircuitBreaker:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500
    instances:
      postServiceRetry:
        baseConfig: default
      commentServiceRetry:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/